#!/bin/bash



#RUN source /etc/bash.bashrc
#ENV NRN_NMODL_PATH $NDIR
#RUN python -c "from pyrho import *; setupNEURON()"

# notebooks created by binder
#COPY index.ipynb /home/main/notebooks/index.ipynb
#RUN jupyter nbconvert --inplace --to notebook *.ipynb
#--output 'index.ipynb'
#USER root
### Copy demonstration notebook and config files to home directory
#find /home/main/notebooks -name '*.ipynb' -exec jupyter nbconvert --to notebook {} --output {} \; && \
#    chown -R main:main /home/main

#COPY jupyter_notebook_config.py $HOME/.jupyter/
#RUN chown -R main:main $HOME/notebooks
# chown -R main:main $NDIR

# Install our custom.js
#COPY resources/custom.js /home/main/.jupyter/custom/

# TODO: Check for /srv/ and /tmp/
#USER root
#COPY resources/templates/ /srv/templates/
#RUN chmod a+rX /srv/templates

# Append tmpnb specific options to the base config
#COPY resources/jupyter_notebook_config.partial.py /tmp/
#cat /tmp/jupyter_notebook_config.partial.py >> /home/main/.jupyter/jupyter_notebook_config.py && \
#    rm /tmp/jupyter_notebook_config.partial.py

# Notebooks w/ extensions that auto-run code must be "trusted" to work the first time
#jupyter trust index.ipynb
find . -name '*.ipynb' -exec jupyter trust {} \;

# Fix matplotlib font cache
#rm -rf /home/main/.matplolib
#rm -rf /home/main/.cache/matplolib
#rm -rf /home/main/.cache/fontconfig
#python -c "import matplotlib.pyplot as plt"

export NEURON_HOME=$HOME/neuron
mkdir $NEURON_HOME

echo $PYTHONPATH
export PYTHONPATH=`which python3` #/usr/local/lib/python3.5/
export PYTHONHOME=/srv/conda # For me it was /Users/rgerkin/miniconda3
export LD_LIBRARY_PATH=$PYTHONHOME/lib
export PATH=$PATH:$NEURON_HOME/nrn/x86_64/bin
export PYTHONPATH=$PYTHONPATH:$NEURON_HOME/nrn/lib/python/

#rm -rf $NEURON_HOME # Get rid of old NEURON installations
#rm -rf $PYTHONHOME/lib/site-packages/neuron # Get rid old old NEURON code installations

#git clone https://github.com/nrnhines/iv.git
git clone https://github.com/nrnhines/nrn.git

#export PYTHON2 = `which python2` # /path/to/your/python2
#$PYTHON2/bin/pip install mercurial
#$PYTHON2/bin/hg clone http://www.neuron.yale.edu/hg/neuron/nrn

cd nrn
sh build.sh
./configure --prefix=$NEURON_HOME/nrn --with-nrnpython=python3 --without-iv  --without-x # don't use "dynamic" since it doesn't actually work
make
sudo make install

#nrniv
python -c "import neuron"

#sudo install_name_tool -change @rpath/libpython3.5m.dylib $MC3/lib/libpython3.5m.dylib $NEURON_HOME/bin/nrniv

export NRN_NMODL_PATH=$NEURON_HOME
python -c "from pyrho import *; setupNEURON()"
